# -*- coding: utf-8 -*-
"""Assignment-4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1asmxv7njCaeINhN2EMGEXk8B0y0FbPyL
"""

import matplotlib.pyplot as plt
import numpy as np
import subprocess
import shlex
# Create the vectors X and Y
x = np.linspace(-4,4,200)
y = x ** 2 - 3
 
# Create the plot
plt.plot(x,y,label='y =x ** 2 - 3 ')
 
# Add a title
plt.title('')
 
# Add X and y Label
plt.xlabel('x axis')
plt.ylabel('y axis')
 
# Add a grid
plt.grid(alpha=1,linestyle='--')
 
# Add a Legend
plt.legend()
plt.savefig
# Show the plot
plt.show()